# JWST_0026
# Audit: Regenerate JWST_0025 and print clickable HTTP image links. Python only. No AI images.

from pathlib import Path
from datetime import datetime, timezone
import sys
import subprocess
import importlib
import urllib.request

VERSION = "JWST_0026"
PROJECT = "SCHWARZSCHILD CLICKABLE IMAGE OUTPUT INDEX"
BASE_SCRIPT = "JWST_0025_SCHWARZSCHILD_DETAIL_AND_UPLOAD.py"
BASE_URL = "https://raw.githubusercontent.com/gear66me-ui/JWST/main/JWST_0025_SCHWARZSCHILD_DETAIL_AND_UPLOAD.py"
OUT = Path("/content/JWST_OUTPUT") if Path("/content").exists() else Path.cwd() / "JWST_OUTPUT"
CSV = OUT / "CSV"
LOCAL_BASE_SCRIPT = Path("/content") / BASE_SCRIPT if Path("/content").exists() else Path.cwd() / BASE_SCRIPT
LINKS_CSV = CSV / "JWST_0025_GITHUB_OUTPUT_LINKS.csv"


def need(pkg, imp=None):
    imp = imp or pkg
    try:
        importlib.import_module(imp)
    except Exception:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])


def print_table(rows, headers):
    widths = [max(len(str(h)), *(len(str(row[i])) for row in rows)) for i, h in enumerate(headers)]
    print(" | ".join(str(h).ljust(widths[i]) for i, h in enumerate(headers)))
    print("-" * (sum(widths) + 3 * (len(widths) - 1)))
    for row in rows:
        print(" | ".join(str(row[i]).ljust(widths[i]) for i in range(len(headers))))


def run_base_script():
    import runpy
    print("REGENERATING PYTHON/MATPLOTLIB OUTPUTS")
    print(f"Source : {BASE_URL}")
    urllib.request.urlretrieve(BASE_URL, LOCAL_BASE_SCRIPT)
    runpy.run_path(str(LOCAL_BASE_SCRIPT), run_name="__main__")


def load_links():
    need("pandas")
    import pandas as pd
    if not LINKS_CSV.exists():
        raise FileNotFoundError(f"Missing link table after regeneration: {LINKS_CSV}")
    df = pd.read_csv(LINKS_CSV)
    if "raw_url" not in df.columns:
        raise ValueError(f"Link table has no raw_url column: {LINKS_CSV}")
    return df


def display_clickable_links(df):
    images = df[df["type"].astype(str).str.lower().eq("png")].copy()
    image_rows = [(row["file"], row["raw_url"]) for _, row in images.iterrows()]
    data_rows = [(row["type"], row["file"], row["raw_url"]) for _, row in df.iterrows()]

    print(f"\nCODE OUTPUT: {VERSION}\n")
    print_table([
        ("Project", PROJECT),
        ("Regenerated by", BASE_SCRIPT),
        ("Output style", "clickable HTTP links printed one per line"),
        ("Image count", len(image_rows)),
        ("Link table", str(LINKS_CSV)),
    ], ["Field", "Value"])

    print("\nIMAGES AVAILABLE HERE:")
    for name, url in image_rows:
        print(f"{name}")
        print(url)

    print("\nALL OUTPUT HTTP LINKS")
    print_table(data_rows, ["Type", "File", "HTTP link"])

    try:
        from IPython.display import HTML, display
        links_html = "".join(
            f'<li><a href="{url}" target="_blank">{name}</a><br><code>{url}</code></li>'
            for name, url in image_rows
        )
        previews_html = "".join(
            f'<h4 style="color:#e5e7eb">{name}</h4>'
            f'<a href="{url}" target="_blank"><img src="{url}" style="max-width:100%;border:1px solid #475569;border-radius:8px"></a>'
            for name, url in image_rows
        )
        html = f"""
        <div style="background:#050712;color:#f8fafc;padding:16px;border-radius:10px;border:1px solid #475569">
          <h2 style="margin-top:0;color:#f8fafc">Images available here</h2>
          <p>Click any image name or preview to open the raw GitHub PNG in a new tab.</p>
          <ul>{links_html}</ul>
          <hr style="border-color:#334155">
          {previews_html}
        </div>
        """
        display(HTML(html))
    except Exception as exc:
        print(f"\nHTML clickable display skipped: {exc}")

    print("\nCOMMENTS")
    print("No AI images. This script calls the Python/matplotlib generator and prints direct GitHub HTTP links.")
    print(datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"))
    print(f"# {VERSION}")


def main():
    need("pandas")
    run_base_script()
    df = load_links()
    display_clickable_links(df)


if __name__ == "__main__":
    main()
